// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Demo03_DBFirst_EFCorePowerTools.Data.Contexts.Configurations;
using Demo03_DBFirst_EFCorePowerTools.Data.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace Demo03_DBFirst_EFCorePowerTools.Data.Contexts;

public partial class NorthwindDbContext : DbContext
{
    public NorthwindDbContext(DbContextOptions<NorthwindDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
